# Generated by Django 3.0.2 on 2020-02-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
