# Generated by Django 3.0.2 on 2020-02-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagerApp', '0003_auto_20200204_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
